### ISSUE TITLE
Reasoning for two requirements.txt files? 

### ISSUE THREAD

**Issue by RusseII** [pillargg/python-starter#1]
What is the reasoning behind having the two separate requirements.txt files? Can you share any other resources you used to come to this decision? 

By the way -> In the future I'd like to document our design decisions using Architectural Decision Records (ADRs)

Example template for an ADR: 

>In the context of <use case/user story u>, facing {concern c} we decided for {option o} and neglected {other options}, to achieve {system qualities/desired consequences}, accepting {downside d/undesired consequences}, because {additional rationale}.

More reading: https://www.infoq.com/articles/sustainable-architectural-design-decisions/

**Comment by RusseII** [comment]
Talked with @chand1012 about this. One of the requirement files is specifically for dev dependencies and the other one is for the actual needed dependencies for the project to run. 

Proposed solution was to have the `requirements.txt` file with everything needed to run, and a 2nd file called `dev-requirements.txt` that only have the dev dependencies.

**Comment by chand1012** [comment]
Solution was fixed with [this](https://github.com/pillargg/python-starter/commit/edc6b9e5ff91928f30af2b8e13a4ebcb8421f143) commit.
