### ISSUE TITLE
Questions about Docker & Docker.deploy

### ISSUE THREAD

**Issue by RusseII** [pillargg/python-starter#2]
Is there a different way we can handle the dockerfiles and the deployment files other than `dockerfile` and `dockerfile.deploy`? An issue that I'm concerned about is someone wanting to modify the docker file and only modifying one of the two files.

Curious about some of the pros and cons of using this method vs others.

**Comment by RusseII** [comment]
@chand1012 btw you'd be able to run different logic inside one dockerfile based on the environment by setting an env variable and using that in the dockerfile

**Comment by chand1012** [comment]
For now I think we should focus on streamlining development by having the same Dockerfile for development and for production.
